SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

GAME_TITLE = "Pong 2024"
FPS = 60 # will explore how to use variable FPS later

PADDLE_WIDTH = 20
PADDLE_HEIGHT = 100

BALL_WIDTH = 20
BALL_HEIGHT = 20

PADDLE_SPEED = 4

BALL_START_ANGLE_MIN = -35
BALL_START_ANGLE_MAX = 35
BALL_START_VELOCITY = 3 # This will result in 9 due to two angles
ANGLE_CHANGE_1 = 15

INC_SPEED_SHOTS = 4